on:
    push:
        branches: [main]


jobs:
  tag:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate Next Tag
        id: version
        shell: bash
        run: |
          LAST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi

          echo "Last tag: $LAST_TAG"

          VERSION=${LAST_TAG#v}

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "Commit message:"
          echo "$COMMIT_MSG"

          if echo "$COMMIT_MSG" | grep -q "BREAKING CHANGE\|feat!"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0

          elif echo "$COMMIT_MSG" | grep -q "^feat"; then
            MINOR=$((MINOR + 1))
            PATCH=0

          else
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "New tag: $NEW_TAG"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and Push Tag
        run: |
          git tag ${{ steps.version.outputs.new_tag }}   
          git push --tags     
      - name: Commit & push version
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          name: Release ${{ steps.version.outputs.new_tag }}
          body: ${{ steps.version.outputs.changelog }}